[KP-856] New Plugin - run puppeteer tests
Kaholo/kaholo-plugin-puppeteer pull request #1
Opened 2022-09-07 09:03 UTC by graddaniel

2022-09-08 09:04 UTC, xkcm requested changes

2022-09-08 09:04 UTC, xkcm commented on package.json
> +    "puppeteer": "^17.0.0"
Carets

2022-09-08 11:17 UTC, Kszemi approved these changes, later dismissed

2022-09-09 13:09 UTC, xkcm approved these changes

2022-09-12 10:04 UTC, Kszemi approved these changes

2022-09-13 08:12 UTC, merged